#!/bin/bash

# Sprawdzenie, czy podano nazwe pliku.
if [ $# -ne 1 ]; then
    echo "Nie podano pliku z logami" >&2
    exit 1
fi

logfile=$1

# Sprawdzenie, czy taki plik istnieje
if [ ! -f "$logfile" ]; then
    echo "Plik $logfile nie istnieje" >&2
    exit 1
fi

awk -F'[:[]' '{count[$3]++} END {for (i=0; i<24; i++) printf "%02d %d\n", i, count[sprintf("%02d", i)]}' "$logfile"