#!/bin/bash

# Sprawdzenie, czy podano nazwe pliku.
if [ $# -ne 1 ]; then
    echo "Nie podano pliku z logami" >&2
    exit 1
fi

logfile=$1

# Sprawdzenie, czy taki plik istnieje
if [ ! -f "$logfile" ]; then
    echo "Plik $logfile nie istnieje" >&2
    exit 1
fi

awk '($6 ~ /GET|POST/) {print $1}' "$logfile" | \
sort | uniq -c | sort -k1,1nr -k2 | head -n 10 | \
awk '{print $2, $1}'